version: '3.4'

services:
    assessment.EventServices.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - "80:80"
        depends_on:
           kafka:
             condition:
               service_healthy
    zookeeper:
        hostname: zookeeper
        healthcheck:
            test: nc -z localhost 2181 || exit -1
            start_period: 15s
            interval: 5s
            timeout: 10s
            retries: 3
    kafka:
        hostname: kafka
        entrypoint: [ '/bin/sh', '-c' ]
        healthcheck:
            test: nc -z localhost 9092 || exit -1
            start_period: 20s
            interval: 5s
            timeout: 20s
            retries: 3