version: '3.4'

services:
  assessment.eventservices.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"
    depends_on:
     kafka:
      condition:
       service_healthy

  assessment.eventservices.elastic.api:
    hostname: assessment.eventservices.elastic.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"

  assessment.eventservices.postgres.api:
    hostname: assessment.eventservices.postgres.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081
    ports:
      - "8081:8081"

  assessment.eventsconsumer:
    depends_on:
     kafka:
      condition:
       service_healthy

  assessment.eventsconsumer.postgres:
    depends_on:
     kafka:
      condition:
       service_healthy
